# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/packages/core'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    groups:
      eslint-updates:
        patterns:
          - '*eslint*'
      storybook-updates:
        patterns:
          - '@storybook/*'
          - 'storybook'
      postcss-updates:
        patterns:
          - '*postcss*'
    labels:
      - 'dependencies'
      - 'npm'
    reviewers:
      - '46ki75'

  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/notion-node'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'npm'
    reviewers:
      - '46ki75'
