version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      eslint-updates:
        patterns:
          - "*eslint*"
      storybook-updates:
        patterns:
          - "@storybook/*"
          - "storybook"
      postcss-updates:
        patterns:
          - "*postcss*"
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "46ki75"

  - package-ecosystem: "terraform"
    directories:
      - "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "Terraform"
    assignees:
      - "46ki75"
