// design-sync only: (re)download the self-hosted webfonts and regenerate
// fonts.css.
//
//   node .design-sync/fonts/fetch.mjs
//
// @elmethis/core defines the font-family token *names* (sans → "DM Sans",
// "Zen Kaku Gothic New"; monospace → "DM Mono") but ships no @font-face/woff2 —
// the host app is expected to provide the actual fonts. claude.ai/design has no
// such host, and headless Chromium carries no Japanese font at all, so we vendor
// an offline copy here. Wired via cfg.extraFonts; the converter copies the
// woff2 into the bundle's fonts/. All files come from @fontsource (Google Fonts,
// OFL) via jsDelivr.
//
// Latin faces use the small `latin` subset; Japanese uses @fontsource's single
// combined `japanese` subset (~1 MB/weight, full coverage — far cleaner than
// Google's ~120 unicode-range slices). Each file stays well under the 5 MB
// per-file upload cap. The font-family stack order (Latin first, then Zen Kaku)
// is what routes CJK glyphs to the Japanese face, so no unicode-range is needed.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const DIR = path.dirname(fileURLToPath(import.meta.url));
const CDN = "https://cdn.jsdelivr.net/npm/@fontsource";

/** family: CSS name · pkg: @fontsource package · subset · [weight, outFile][] */
const FONTS = [
  {
    family: "DM Sans",
    pkg: "dm-sans",
    subset: "latin",
    weights: [
      [400, "dm-sans-400.woff2"],
      [500, "dm-sans-500.woff2"],
      [700, "dm-sans-700.woff2"],
    ],
  },
  {
    family: "DM Mono",
    pkg: "dm-mono",
    subset: "latin",
    weights: [
      [400, "dm-mono-400.woff2"],
      [500, "dm-mono-500.woff2"],
    ],
  },
  {
    family: "Source Code Pro",
    pkg: "source-code-pro",
    subset: "latin",
    weights: [[400, "source-code-pro-400.woff2"]],
  },
  {
    family: "Zen Kaku Gothic New",
    pkg: "zen-kaku-gothic-new",
    subset: "japanese",
    weights: [
      [400, "zen-kaku-gothic-new-400.woff2"],
      [700, "zen-kaku-gothic-new-700.woff2"],
    ],
  },
];

const faces = [];
for (const font of FONTS) {
  for (const [weight, out] of font.weights) {
    const url = `${CDN}/${font.pkg}/files/${font.pkg}-${font.subset}-${weight}-normal.woff2`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await writeFile(path.join(DIR, out), buf);
    console.error(`fetched ${out} (${buf.length} bytes)`);
    faces.push(
      [
        "@font-face {",
        `  font-family: "${font.family}";`,
        "  font-style: normal;",
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("./${out}") format("woff2");`,
        "}",
      ].join("\n"),
    );
  }
}

const header = `/*
 * design-sync only — self-hosted webfonts for claude.ai/design.
 * GENERATED by fetch.mjs; do not edit by hand. Run \`node .design-sync/fonts/fetch.mjs\`
 * to refresh. Sources: @fontsource (Google Fonts, OFL). See fetch.mjs for why
 * these are vendored (core ships token names, not @font-face).
 */
`;
await writeFile(
  path.join(DIR, "fonts.css"),
  header + "\n" + faces.join("\n") + "\n",
);
console.error(`wrote fonts.css (${faces.length} @font-face blocks)`);
