name: Build Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  notion-node:
    name: Build Test (@elmethis/notion-node)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22.x

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --recursive

      - name: Run Build Test
        run: pnpm run build
        working-directory: packages/notion-node

  core:
    name: Build Test (@elmethis/core)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22.x

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --recursive

      - name: Run Build Test
        run: pnpm run build
        working-directory: packages/core
